# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
